// Disney movie trivia — grown-up party edition.
// Server-side ONLY. The answer key never reaches players' browsers; the API
// sends question text + options during play and reveals `correct` afterward.
//
// Each question: { q, category, options:[4 strings], correct: index 0-3, fact }
// `fact` is a fun blurb shown on the host screen at reveal time.

const QUESTIONS = [
  {
    q: "Disney's very first full-length animated feature was…",
    category: "Classics",
    options: ["Pinocchio", "Snow White and the Seven Dwarfs", "Fantasia", "Cinderella"],
    correct: 1,
    fact: "1937. Critics called it 'Disney's Folly' — it went on to be the highest-grossing film of its time.",
  },
  {
    q: "Who voiced the Genie in the 1992 animated 'Aladdin'?",
    category: "Voice Actors",
    options: ["Robin Williams", "Eddie Murphy", "Jim Carrey", "Steve Martin"],
    correct: 0,
    fact: "Robin Williams improvised so much that the film was disqualified from a Best Screenplay nod.",
  },
  {
    q: "In 'The Lion King,' 'Hakuna Matata' means…",
    category: "Songs",
    options: ["No worries", "Be brave", "Good morning", "The circle of life"],
    correct: 0,
    fact: "It's real Swahili — 'hakuna matata' literally means 'there are no troubles.'",
  },
  {
    q: "What kind of toy is Buzz Lightyear?",
    category: "Pixar",
    options: ["Astronaut doll", "Space Ranger action figure", "Toy robot", "Alien plush"],
    correct: 1,
    fact: "Buzz was nearly named 'Lunar Larry.' He's named after astronaut Buzz Aldrin.",
  },
  {
    q: "The sea witch in 'The Little Mermaid' is named…",
    category: "Villains",
    options: ["Maleficent", "Ursula", "Cruella", "Yzma"],
    correct: 1,
    fact: "Ursula's look was famously inspired by the drag performer Divine.",
  },
  {
    q: "'Let It Go' is the showstopper from which film?",
    category: "Songs",
    options: ["Moana", "Tangled", "Frozen", "Encanto"],
    correct: 2,
    fact: "It won the 2014 Oscar for Best Original Song — and never left your head again.",
  },
  {
    q: "In 'Beauty and the Beast,' the uptight clock is named…",
    category: "Deep Cuts",
    options: ["Lumière", "Cogsworth", "Chip", "Mrs. Potts"],
    correct: 1,
    fact: "Cogsworth was voiced by David Ogden Stiers — Major Winchester from 'M*A*S*H.'",
  },
  {
    q: "Who voiced Woody in the 'Toy Story' films?",
    category: "Voice Actors",
    options: ["Tim Allen", "Tom Hanks", "Billy Crystal", "John Ratzenberger"],
    correct: 1,
    fact: "Tom Hanks' brother Jim voices Woody in the theme parks and video games.",
  },
  {
    q: "What kind of fish is Dory in 'Finding Nemo'?",
    category: "Pixar",
    options: ["Clownfish", "Regal blue tang", "Pufferfish", "Seahorse"],
    correct: 1,
    fact: "Ellen DeGeneres was cast years before the film finished — they wrote Dory around her.",
  },
  {
    q: "The villain of 'Sleeping Beauty' is…",
    category: "Villains",
    options: ["Maleficent", "The Evil Queen", "Lady Tremaine", "Madame Medusa"],
    correct: 0,
    fact: "Maleficent calls herself the 'Mistress of All Evil.' Hard to argue.",
  },
  {
    q: "'A Whole New World' is the Oscar-winning ballad from…",
    category: "Songs",
    options: ["Aladdin", "Hercules", "Mulan", "Tarzan"],
    correct: 0,
    fact: "It's the only Disney song to ever win the Grammy for Song of the Year.",
  },
  {
    q: "What year did Disneyland open in Anaheim, California?",
    category: "Deep Cuts",
    options: ["1949", "1955", "1961", "1971"],
    correct: 1,
    fact: "Opening day, July 17, 1955, was such a disaster staff dubbed it 'Black Sunday.'",
  },
  {
    q: "Who wants to turn a litter of puppies into a fur coat?",
    category: "Villains",
    options: ["Cruella de Vil", "Ursula", "Madame Medusa", "Yzma"],
    correct: 0,
    fact: "'Cruella de Vil' is barely even hiding it — say it slowly.",
  },
  {
    q: "Who voiced Elsa in 'Frozen'?",
    category: "Voice Actors",
    options: ["Kristen Bell", "Idina Menzel", "Auli'i Cravalho", "Mandy Moore"],
    correct: 1,
    fact: "Idina Menzel first won a Tony originating Elphaba in Broadway's 'Wicked' — another green-tinged powerhouse.",
  },
  {
    q: "In 'Monsters, Inc.,' the little girl Sulley befriends is named…",
    category: "Pixar",
    options: ["Boo", "Riley", "Dot", "Darla"],
    correct: 0,
    fact: "Her real name is Mary — 'Boo' is just what Sulley calls her.",
  },
  {
    q: "'You've Got a Friend in Me' was written and sung by…",
    category: "Songs",
    options: ["Elton John", "Randy Newman", "Phil Collins", "Billy Joel"],
    correct: 1,
    fact: "Randy Newman has 22 Oscar nominations — and finally won for this film's franchise.",
  },
  {
    q: "In 'Aladdin,' Jafar's sarcastic parrot is named…",
    category: "Deep Cuts",
    options: ["Iago", "Zazu", "Diablo", "Rafiki"],
    correct: 0,
    fact: "Named for the villain in Shakespeare's 'Othello.' Voiced by Gilbert Gottfried.",
  },
  {
    q: "'Coco' unfolds during which Mexican holiday?",
    category: "Pixar",
    options: ["Cinco de Mayo", "Día de los Muertos", "Las Posadas", "Carnival"],
    correct: 1,
    fact: "The marigold-petal bridge is inspired by real Day of the Dead ofrendas.",
  },
  {
    q: "Who kills Mufasa in 'The Lion King'?",
    category: "Villains",
    options: ["Scar", "The hyenas", "A rival lion", "Zira"],
    correct: 0,
    fact: "'Long live the king.' Scar's line still ruins childhoods to this day.",
  },
  {
    q: "In 'Cinderella,' the fairy godmother turns WHAT into a coach?",
    category: "Classics",
    options: ["A pumpkin", "A watermelon", "A rock", "A haystack"],
    correct: 0,
    fact: "Bibbidi-bobbidi-boo — and four mice became the horses.",
  },
  {
    q: "Who provides the singing voice of Moana?",
    category: "Voice Actors",
    options: ["Auli'i Cravalho", "Zendaya", "Idina Menzel", "Kristen Bell"],
    correct: 0,
    fact: "Auli'i was 14 and had submitted her audition tape almost as an afterthought.",
  },
  {
    q: "Which Pixar movie was the studio's first full-length feature?",
    category: "Pixar",
    options: ["Toy Story", "A Bug's Life", "Monsters, Inc.", "Finding Nemo"],
    correct: 0,
    fact: "1995 — the first entirely computer-animated feature film ever made.",
  },
  {
    q: "In 'Peter Pan,' the pixie who sprinkles fairy dust is…",
    category: "Classics",
    options: ["Tinker Bell", "Wendy", "Silvermist", "Periwinkle"],
    correct: 0,
    fact: "Tinker Bell 'speaks' only in the chime of tiny bells.",
  },
  {
    q: "In 'Up,' how does Carl move his house?",
    category: "Pixar",
    options: ["Thousands of balloons", "A crane", "A tornado", "Strapped-on rockets"],
    correct: 0,
    fact: "The opening 'Married Life' montage still makes grown adults cry in four minutes flat.",
  },
  {
    q: "Which dwarf in 'Snow White' wears glasses and leads the group?",
    category: "Classics",
    options: ["Doc", "Grumpy", "Bashful", "Happy"],
    correct: 0,
    fact: "The seven were almost named Jumpy, Deafy, Dizzey, Hickey, Wheezy, Baldy and Nifty.",
  },
  {
    q: "In 'Hercules,' Hades' two bumbling minions are named…",
    category: "Deep Cuts",
    options: ["Pain and Panic", "Flotsam and Jetsam", "Thug 1 and Thug 2", "Bing and Bong"],
    correct: 0,
    fact: "James Woods ad-libbed so much as Hades that Disney kept re-hiring him for the role.",
  },
  {
    q: "Which crab sings 'Under the Sea' in 'The Little Mermaid'?",
    category: "Songs",
    options: ["Sebastian", "Flounder", "Scuttle", "King Triton"],
    correct: 0,
    fact: "'Under the Sea' won the Oscar for Best Original Song in 1990.",
  },
  {
    q: "What is the name of the kingdom in 'Frozen'?",
    category: "Deep Cuts",
    options: ["Arendelle", "Corona", "DunBroch", "Genovia"],
    correct: 0,
    fact: "Arendelle's design is based on the real Norwegian port town of Bergen.",
  },
  {
    q: "What kind of animal is Baloo in 'The Jungle Book'?",
    category: "Classics",
    options: ["A bear", "A panther", "A tiger", "An orangutan"],
    correct: 0,
    fact: "'The Bare Necessities' was nominated for an Oscar in 1968.",
  },
  {
    q: "In the original 'Toy Story,' the destructive kid next door is…",
    category: "Pixar",
    options: ["Sid", "Al", "Andy", "Buster"],
    correct: 0,
    fact: "A Pixar animator's own toy-torturing childhood neighbor inspired Sid.",
  },
  {
    q: "'Circle of Life' opens which Disney film?",
    category: "Songs",
    options: ["The Lion King", "Tarzan", "Brother Bear", "The Jungle Book"],
    correct: 0,
    fact: "Elton John and Tim Rice wrote it; the Zulu opening chant translates to 'Here comes a lion.'",
  },
  {
    q: "Roughly how long is Rapunzel's magic hair in 'Tangled'?",
    category: "Deep Cuts",
    options: ["30 feet", "50 feet", "70 feet", "100 feet"],
    correct: 2,
    fact: "About 70 feet — animators built special software just to make it move.",
  },
  {
    q: "Mickey Mouse's loyal pet dog is named…",
    category: "Classics",
    options: ["Goofy", "Pluto", "Max", "Dinah"],
    correct: 1,
    fact: "Pluto and Goofy are both dogs — but only Goofy gets to talk and wear pants.",
  },
  {
    q: "In 'Ratatouille,' the famous Paris restaurant is called…",
    category: "Pixar",
    options: ["Gusteau's", "Chez Remy", "Le Petit Chef", "La Ratatouille"],
    correct: 0,
    fact: "'Anyone can cook.' Chef Gusteau's motto drives the whole film.",
  },
  {
    q: "Which teapot sings the title song in 'Beauty and the Beast'?",
    category: "Songs",
    options: ["Mrs. Potts", "The Wardrobe", "Fifi the feather duster", "Belle"],
    correct: 0,
    fact: "Mrs. Potts was voiced by Angela Lansbury, who recorded the ballad in a single take.",
  },
  {
    q: "In 'Mulan,' what is the name of the little red dragon sidekick?",
    category: "Deep Cuts",
    options: ["Mushu", "Cri-Kee", "Shan Yu", "Khan"],
    correct: 0,
    fact: "Eddie Murphy voiced Mushu — a warm-up for his role as Donkey in 'Shrek.'",
  },
];

module.exports = QUESTIONS;
