// Disney movie trivia — grown-up party edition, category-driven.
// Server-side ONLY. The answer key never reaches players' browsers.
//
// Each question: { q, cat, options:[4], correct: 0-3, fact }
//   `cat` is one of the CATEGORIES keys below.
//   `fact` is a fun blurb shown on the host screen at reveal time.

const CATEGORIES = [
  { key: "classics",    label: "Golden Age Classics", emoji: "🏰" },
  { key: "renaissance", label: "Disney Renaissance",  emoji: "🌹" },
  { key: "pixar",       label: "Pixar",               emoji: "💡" },
  { key: "modern",      label: "Modern Disney",       emoji: "❄️" },
  { key: "villains",    label: "Villains",            emoji: "😈" },
  { key: "songs",       label: "Songs & Music",       emoji: "🎵" },
  { key: "voices",      label: "Voice Actors",        emoji: "🎙️" },
  { key: "funfacts",    label: "Fun Facts & Trivia",  emoji: "✨" },
];

const QUESTIONS = [
  // ============================ GOLDEN AGE CLASSICS ============================
  { cat: "classics", q: "Disney's very first full-length animated feature was…", options: ["Pinocchio", "Snow White and the Seven Dwarfs", "Fantasia", "Cinderella"], correct: 1, fact: "1937. Critics called it 'Disney's Folly' — it became the highest-grossing film of its era." },
  { cat: "classics", q: "Which dwarf in 'Snow White' wears glasses and leads the group?", options: ["Doc", "Grumpy", "Bashful", "Happy"], correct: 0, fact: "The seven were almost named Jumpy, Deafy, Dizzey, Hickey, Wheezy, Baldy and Nifty." },
  { cat: "classics", q: "In 'Cinderella,' the fairy godmother turns WHAT into a coach?", options: ["A pumpkin", "A watermelon", "A rock", "A haystack"], correct: 0, fact: "Bibbidi-bobbidi-boo — and four mice became the horses." },
  { cat: "classics", q: "What does Cinderella leave behind at the ball?", options: ["A glass slipper", "Her tiara", "A glove", "Her necklace"], correct: 0, fact: "In many older versions the slipper was fur — a mistranslation may have turned it to glass." },
  { cat: "classics", q: "In 'Peter Pan,' the pixie who sprinkles fairy dust is…", options: ["Tinker Bell", "Wendy", "Silvermist", "Periwinkle"], correct: 0, fact: "Tinker Bell 'speaks' only in the chime of tiny bells." },
  { cat: "classics", q: "What kind of animal is Baloo in 'The Jungle Book'?", options: ["A bear", "A panther", "A tiger", "An orangutan"], correct: 0, fact: "'The Bare Necessities' was nominated for an Oscar in 1968." },
  { cat: "classics", q: "In 'Bambi,' what is the name of the young rabbit?", options: ["Thumper", "Flower", "Bongo", "Bucky"], correct: 0, fact: "'If you can't say something nice… don't say nothin' at all' — Thumper's mother, forever quoted." },
  { cat: "classics", q: "In 'Alice in Wonderland,' who is always fretting about being late?", options: ["The White Rabbit", "The Cheshire Cat", "The Mad Hatter", "The March Hare"], correct: 0, fact: "'I'm late, I'm late, for a very important date!'" },
  { cat: "classics", q: "What makes Dumbo special?", options: ["His giant ears let him fly", "His trunk grants wishes", "His tail glows", "His singing voice"], correct: 0, fact: "At 64 minutes, 'Dumbo' is one of Disney's shortest animated features." },
  { cat: "classics", q: "Who serves as Pinocchio's conscience?", options: ["Jiminy Cricket", "Figaro", "Cleo", "Geppetto"], correct: 0, fact: "Jiminy sings 'When You Wish Upon a Star,' now the whole studio's anthem." },
  { cat: "classics", q: "In 'The Sword in the Stone,' who is destined to become king?", options: ["Arthur (Wart)", "Merlin", "Lancelot", "Sir Kay"], correct: 0, fact: "Merlin mentors young Arthur — and turns him into a squirrel and a fish along the way." },
  { cat: "classics", q: "In Disney's 1973 'Robin Hood,' Robin is depicted as what animal?", options: ["A fox", "A bear", "A lion", "A rooster"], correct: 0, fact: "Little John is a bear who looks suspiciously like Baloo — same animators, same model." },
  { cat: "classics", q: "In 'Lady and the Tramp,' the famous shared meal is…", options: ["Spaghetti and meatballs", "Pizza", "Fried chicken", "Ice cream"], correct: 0, fact: "The nose-to-nose meatball nudge wasn't in early drafts — Walt nearly cut the whole scene." },
  { cat: "classics", q: "In 'The Aristocats,' what is the elegant mother cat's name?", options: ["Duchess", "Marie", "Berlioz", "Toulouse"], correct: 0, fact: "It was the last film Walt Disney personally approved before his death in 1966." },
  { cat: "classics", q: "How does the Evil Queen learn she's the fairest of them all?", options: ["The Magic Mirror", "A crystal ball", "A talking raven", "The stars"], correct: 0, fact: "'Magic Mirror on the wall…' — note it's never actually 'Mirror, mirror.'" },

  // ============================ DISNEY RENAISSANCE ============================
  { cat: "renaissance", q: "The sea witch in 'The Little Mermaid' is named…", options: ["Maleficent", "Ursula", "Cruella", "Yzma"], correct: 1, fact: "Ursula's look was famously inspired by the drag performer Divine." },
  { cat: "renaissance", q: "Ariel's father, ruler of the sea, is…", options: ["King Triton", "Poseidon", "King Neptune", "Sebastian"], correct: 0, fact: "Triton's booming voice was provided by Kenneth Mars." },
  { cat: "renaissance", q: "In 'Beauty and the Beast,' the uptight clock is named…", options: ["Lumière", "Cogsworth", "Chip", "Mrs. Potts"], correct: 1, fact: "Cogsworth was voiced by David Ogden Stiers — Major Winchester from 'M*A*S*H.'" },
  { cat: "renaissance", q: "The charming candelabra in 'Beauty and the Beast' is…", options: ["Lumière", "Cogsworth", "Chip", "Maurice"], correct: 0, fact: "'Be Our Guest' racks up a dizzying number of dancing dishes and flatware." },
  { cat: "renaissance", q: "In 'Aladdin,' Jafar's sarcastic parrot is named…", options: ["Iago", "Zazu", "Diablo", "Rafiki"], correct: 0, fact: "Named for the villain in Shakespeare's 'Othello.' Voiced by Gilbert Gottfried." },
  { cat: "renaissance", q: "What is the name of Aladdin's mischievous monkey?", options: ["Abu", "Rajah", "Iago", "Genie"], correct: 0, fact: "Abu is named after the guide in the 1940 film 'The Thief of Bagdad.'" },
  { cat: "renaissance", q: "In 'The Lion King,' the wise mandrill shaman is…", options: ["Rafiki", "Zazu", "Mufasa", "Scar"], correct: 0, fact: "'Rafiki' means 'friend' in Swahili." },
  { cat: "renaissance", q: "Which meerkat-and-warthog duo adopt Simba?", options: ["Timon and Pumbaa", "Ed and Banzai", "Nala and Sarabi", "Zazu and Rafiki"], correct: 0, fact: "Nathan Lane and Ernie Sabella originally auditioned to play the hyenas." },
  { cat: "renaissance", q: "In 'Mulan,' what is the name of the little red dragon sidekick?", options: ["Mushu", "Cri-Kee", "Shan Yu", "Khan"], correct: 0, fact: "Eddie Murphy voiced Mushu — a warm-up for his role as Donkey in 'Shrek.'" },
  { cat: "renaissance", q: "In 'Hercules,' Hades' two bumbling minions are named…", options: ["Pain and Panic", "Flotsam and Jetsam", "Thug 1 and Thug 2", "Bing and Bong"], correct: 0, fact: "James Woods ad-libbed so much as Hades that Disney kept re-hiring him for the role." },
  { cat: "renaissance", q: "In 'Pocahontas,' what is the name of the playful raccoon?", options: ["Meeko", "Flit", "Percy", "Kocoum"], correct: 0, fact: "Flit the hummingbird is his constant frenemy." },
  { cat: "renaissance", q: "The bell-ringer of Notre Dame is named…", options: ["Quasimodo", "Frollo", "Phoebus", "Clopin"], correct: 0, fact: "His gargoyle friends are Victor, Hugo and Laverne — a nod to author Victor Hugo." },
  { cat: "renaissance", q: "In 'Tarzan,' the gorilla who raises Tarzan as her own is…", options: ["Kala", "Kerchak", "Terk", "Jane"], correct: 0, fact: "Phil Collins performed the film's Oscar-winning song, 'You'll Be in My Heart.'" },
  { cat: "renaissance", q: "In 'The Little Mermaid,' which crab is Ariel's reluctant chaperone?", options: ["Sebastian", "Flounder", "Scuttle", "Triton"], correct: 0, fact: "Sebastian's full name is Horatio Thelonious Ignacious Crustaceous Sebastian." },
  { cat: "renaissance", q: "What is the name of Jasmine's pet tiger in 'Aladdin'?", options: ["Rajah", "Abu", "Iago", "Sultan"], correct: 0, fact: "Rajah once nearly took a bite out of an unwanted suitor, Prince Achmed." },

  // ============================ PIXAR ============================
  { cat: "pixar", q: "What kind of toy is Buzz Lightyear?", options: ["Astronaut doll", "Space Ranger action figure", "Toy robot", "Alien plush"], correct: 1, fact: "Buzz was nearly named 'Lunar Larry.' He's named after astronaut Buzz Aldrin." },
  { cat: "pixar", q: "In the original 'Toy Story,' the destructive kid next door is…", options: ["Sid", "Al", "Andy", "Buster"], correct: 0, fact: "A Pixar animator's own toy-torturing childhood neighbor inspired Sid." },
  { cat: "pixar", q: "What kind of fish is Dory in 'Finding Nemo'?", options: ["Clownfish", "Regal blue tang", "Pufferfish", "Seahorse"], correct: 1, fact: "Ellen DeGeneres was cast years before the film finished — they wrote Dory around her." },
  { cat: "pixar", q: "In 'Monsters, Inc.,' the little girl Sulley befriends is named…", options: ["Boo", "Riley", "Dot", "Darla"], correct: 0, fact: "Her real name is Mary — 'Boo' is just what Sulley calls her." },
  { cat: "pixar", q: "Who is Sulley's wisecracking one-eyed best friend?", options: ["Mike Wazowski", "Randall", "Roz", "Celia"], correct: 0, fact: "Billy Crystal turned down voicing Buzz Lightyear — then took the Mike role to make up for it." },
  { cat: "pixar", q: "In 'Up,' how does Carl move his house?", options: ["Thousands of balloons", "A crane", "A tornado", "Strapped-on rockets"], correct: 0, fact: "The opening 'Married Life' montage still makes grown adults cry in four minutes flat." },
  { cat: "pixar", q: "What is the name of the talking dog in 'Up'?", options: ["Dug", "Kevin", "Alpha", "Russell"], correct: 0, fact: "'SQUIRREL!' Dug's collar translates his thoughts into speech." },
  { cat: "pixar", q: "In 'Ratatouille,' the rat who dreams of cooking is named…", options: ["Remy", "Emile", "Linguini", "Gusteau"], correct: 0, fact: "Real chef Thomas Keller designed the film's signature ratatouille dish." },
  { cat: "pixar", q: "'Coco' unfolds during which Mexican holiday?", options: ["Cinco de Mayo", "Día de los Muertos", "Las Posadas", "Carnival"], correct: 1, fact: "The marigold-petal bridge is inspired by real Day of the Dead ofrendas." },
  { cat: "pixar", q: "What is the name of Miguel's loyal dog in 'Coco'?", options: ["Dante", "Pepita", "Héctor", "Ernesto"], correct: 0, fact: "Dante is a Xoloitzcuintli — Mexico's hairless national dog." },
  { cat: "pixar", q: "What racing number does Lightning McQueen wear in 'Cars'?", options: ["95", "43", "51", "86"], correct: 0, fact: "95 is a nod to 1995 — the year 'Toy Story' launched Pixar features." },
  { cat: "pixar", q: "In 'Inside Out,' which is NOT one of Riley's five core emotions?", options: ["Disgust", "Love", "Anger", "Fear"], correct: 1, fact: "The five are Joy, Sadness, Fear, Anger and Disgust." },
  { cat: "pixar", q: "In 'The Incredibles,' the super-fast son is named…", options: ["Dash", "Jack-Jack", "Bob", "Buddy"], correct: 0, fact: "Violet turns invisible; Jack-Jack turns out to have… a lot going on." },
  { cat: "pixar", q: "In 'WALL-E,' what is the name of the sleek robot WALL-E falls for?", options: ["EVE", "M-O", "AUTO", "GO-4"], correct: 0, fact: "Sound designer Ben Burtt — of Star Wars fame — created both robots' voices." },
  { cat: "pixar", q: "Which catchphrase belongs to Buzz Lightyear, not Woody?", options: ["To infinity and beyond!", "Reach for the sky!", "There's a snake in my boot!", "Yee-haw!"], correct: 0, fact: "Woody's pull-string only had a handful of phrases — Buzz got the cosmic one." },
  { cat: "pixar", q: "Which Pixar film was the studio's first full-length feature?", options: ["Toy Story", "A Bug's Life", "Monsters, Inc.", "Finding Nemo"], correct: 0, fact: "1995 — the first entirely computer-animated feature film ever made." },

  // ============================ MODERN DISNEY ============================
  { cat: "modern", q: "What is the name of the kingdom in 'Frozen'?", options: ["Arendelle", "Corona", "DunBroch", "Genovia"], correct: 0, fact: "Arendelle's design is based on the real Norwegian port town of Bergen." },
  { cat: "modern", q: "What is the name of the snowman in 'Frozen'?", options: ["Olaf", "Sven", "Kristoff", "Marshmallow"], correct: 0, fact: "'Some people are worth melting for.' Josh Gad improvised many of Olaf's lines." },
  { cat: "modern", q: "What is Kristoff's reindeer named in 'Frozen'?", options: ["Sven", "Olaf", "Maximus", "Angus"], correct: 0, fact: "Kristoff often 'speaks' for Sven in a goofy voice." },
  { cat: "modern", q: "In 'Moana,' the shape-shifting demigod is named…", options: ["Maui", "Tamatoa", "Chief Tui", "Heihei"], correct: 0, fact: "Dwayne Johnson sings 'You're Welcome' — his first movie musical number." },
  { cat: "modern", q: "What kind of animal is Moana's dim-witted travel companion Heihei?", options: ["A rooster", "A pig", "A goat", "A parrot"], correct: 0, fact: "Her pet pig Pua was cut from the ocean voyage for being too sensible." },
  { cat: "modern", q: "Roughly how long is Rapunzel's magic hair in 'Tangled'?", options: ["30 feet", "50 feet", "70 feet", "100 feet"], correct: 2, fact: "About 70 feet — animators built special software just to make it move." },
  { cat: "modern", q: "What is the name of Rapunzel's chameleon in 'Tangled'?", options: ["Pascal", "Maximus", "Flynn", "Pua"], correct: 0, fact: "Maximus the palace horse behaves more like a bloodhound than a stallion." },
  { cat: "modern", q: "In 'The Princess and the Frog,' which city is the setting?", options: ["New Orleans", "Miami", "Atlanta", "Savannah"], correct: 0, fact: "Tiana is Disney's first African American princess, and a chef with a dream." },
  { cat: "modern", q: "What is the family surname in 'Encanto'?", options: ["Madrigal", "Guzmán", "Encanto", "Casita"], correct: 0, fact: "Every Madrigal child receives a magical gift — except, it seems, Mirabel." },
  { cat: "modern", q: "Complete the 'Encanto' hit: 'We Don't Talk About ___.'", options: ["Bruno", "Pedro", "Antonio", "Camilo"], correct: 0, fact: "It knocked 'Let It Go' off Disney's song throne, topping the Billboard Hot 100." },
  { cat: "modern", q: "In 'Zootopia,' the determined rabbit police officer is named…", options: ["Judy Hopps", "Nick Wilde", "Chief Bogo", "Flash"], correct: 0, fact: "The slowest DMV sloth is named Flash — Disney's cheekiest joke." },
  { cat: "modern", q: "In 'Wreck-It Ralph,' what is the name of Ralph's arcade game?", options: ["Fix-It Felix Jr.", "Sugar Rush", "Hero's Duty", "Turbo Time"], correct: 0, fact: "Real game cameos include Sonic, Bowser, and Q*bert." },
  { cat: "modern", q: "In 'Big Hero 6,' the huggable healthcare robot is named…", options: ["Baymax", "Hiro", "Tadashi", "Fred"], correct: 0, fact: "'Are you satisfied with your care?' Baymax is loosely set in 'San Fransokyo.'" },
  { cat: "modern", q: "In 'Lilo & Stitch,' Stitch is known as Experiment number…", options: ["626", "007", "101", "42"], correct: 0, fact: "Stitch was designed by Chris Sanders, who also gave him his voice." },
  { cat: "modern", q: "In 'Raya and the Last Dragon,' the last dragon is named…", options: ["Sisu", "Namaari", "Tuk Tuk", "Raya"], correct: 0, fact: "Awkwafina voices Sisu; the land of Kumandra is inspired by Southeast Asia." },

  // ============================ VILLAINS ============================
  { cat: "villains", q: "Which villain sings 'Poor Unfortunate Souls'?", options: ["Ursula", "Maleficent", "Cruella", "Yzma"], correct: 0, fact: "Ursula strikes her deal in a contract with very fine print." },
  { cat: "villains", q: "In 'Sleeping Beauty,' Maleficent transforms into what to fight the prince?", options: ["A dragon", "A raven", "A serpent", "A wolf"], correct: 0, fact: "'Now shall you deal with ME, O Prince — and all the powers of HELL!'" },
  { cat: "villains", q: "Which villainous song does Scar perform in 'The Lion King'?", options: ["Be Prepared", "Poor Unfortunate Souls", "Friends on the Other Side", "Mother Knows Best"], correct: 0, fact: "Its goose-stepping hyenas make it one of Disney's most theatrical numbers." },
  { cat: "villains", q: "Who wants to turn a litter of puppies into a fur coat?", options: ["Cruella de Vil", "Madame Medusa", "Ursula", "Yzma"], correct: 0, fact: "'Cruella de Vil' is barely even hiding it — say it slowly." },
  { cat: "villains", q: "In 'Tangled,' the villain who keeps Rapunzel locked away is…", options: ["Mother Gothel", "The Evil Queen", "Lady Tremaine", "Ursula"], correct: 0, fact: "Her song 'Mother Knows Best' is a masterclass in gaslighting." },
  { cat: "villains", q: "Which character turns out to be the real villain of 'Frozen'?", options: ["Prince Hans", "Kristoff", "Duke of Weselton", "Olaf"], correct: 0, fact: "The twist was hidden so well that even Hans' animators were surprised late in production." },
  { cat: "villains", q: "In 'The Princess and the Frog,' the shadowy voodoo villain is…", options: ["Dr. Facilier", "Naveen", "Lawrence", "Ray"], correct: 0, fact: "Keith David gives 'Friends on the Other Side' its slinky menace." },
  { cat: "villains", q: "In 'The Emperor's New Groove,' the scheming villainess is…", options: ["Yzma", "Cruella", "Ursula", "Madame Medusa"], correct: 0, fact: "Her lovable henchman Kronk can literally speak Squirrel." },
  { cat: "villains", q: "In 'Peter Pan,' what does Captain Hook fear most?", options: ["The ticking crocodile", "Peter Pan", "Deep water", "Tinker Bell"], correct: 0, fact: "The croc swallowed a clock — so Hook always hears it coming." },
  { cat: "villains", q: "In 'Toy Story 3,' the villainous bear Lotso smells of…", options: ["Strawberries", "Vanilla", "Chocolate", "Cinnamon"], correct: 0, fact: "Lots-o'-Huggin' Bear runs Sunnyside Daycare like a tiny prison warden." },
  { cat: "villains", q: "In 'Zootopia,' who is the surprise mastermind behind the plot?", options: ["Assistant Mayor Bellwether", "Mayor Lionheart", "Mr. Big", "Chief Bogo"], correct: 0, fact: "The meek little sheep was hiding in plain sight the whole time." },
  { cat: "villains", q: "In 'The Rescuers,' the villain who hunts for a diamond is…", options: ["Madame Medusa", "Cruella", "Ursula", "Yzma"], correct: 0, fact: "She forces the orphan Penny down a dark cave to find the 'Devil's Eye' diamond." },
  { cat: "villains", q: "In 'Monsters, Inc.,' which chameleon-like monster is the villain?", options: ["Randall", "Mike", "Roz", "George"], correct: 0, fact: "Steve Buscemi's slippery delivery makes Randall extra unnerving." },
  { cat: "villains", q: "In 'Aladdin,' what does Jafar ultimately wish to become — sealing his fate?", options: ["An all-powerful genie", "The Sultan", "A sorcerer", "A prince"], correct: 0, fact: "He forgets: genies are bound to a lamp. 'Phenomenal cosmic powers… itty-bitty living space.'" },
  { cat: "villains", q: "'The Nightmare Before Christmas' villain who gambles with his victims is…", options: ["Oogie Boogie", "Jack Skellington", "Dr. Finkelstein", "The Mayor"], correct: 0, fact: "Oogie is a burlap sack full of bugs — and one very jazzy musical number." },

  // ============================ SONGS & MUSIC ============================
  { cat: "songs", q: "'Let It Go' is the showstopper from which film?", options: ["Moana", "Tangled", "Frozen", "Encanto"], correct: 2, fact: "It won the 2014 Oscar for Best Original Song — and never left your head again." },
  { cat: "songs", q: "'A Whole New World' is the Oscar-winning ballad from…", options: ["Aladdin", "Hercules", "Mulan", "Tarzan"], correct: 0, fact: "It's the only Disney song to ever win the Grammy for Song of the Year." },
  { cat: "songs", q: "Which crab sings 'Under the Sea' in 'The Little Mermaid'?", options: ["Sebastian", "Flounder", "Scuttle", "King Triton"], correct: 0, fact: "'Under the Sea' won the Oscar for Best Original Song in 1990." },
  { cat: "songs", q: "'Circle of Life' opens which Disney film?", options: ["The Lion King", "Tarzan", "Brother Bear", "The Jungle Book"], correct: 0, fact: "The Zulu opening chant roughly translates to 'Here comes a lion.'" },
  { cat: "songs", q: "'You've Got a Friend in Me' was written and sung by…", options: ["Elton John", "Randy Newman", "Phil Collins", "Billy Joel"], correct: 1, fact: "Randy Newman has over 20 Oscar nominations — and finally won for this franchise." },
  { cat: "songs", q: "'How Far I'll Go' is the yearning anthem from which film?", options: ["Moana", "Frozen", "Tangled", "Brave"], correct: 0, fact: "Lin-Manuel Miranda co-wrote it at the height of his 'Hamilton' fame." },
  { cat: "songs", q: "Which teapot sings the title song in 'Beauty and the Beast'?", options: ["Mrs. Potts", "The Wardrobe", "Belle", "Fifi"], correct: 0, fact: "Mrs. Potts was voiced by Angela Lansbury, who recorded the ballad in a single take." },
  { cat: "songs", q: "'Colors of the Wind' is the Oscar-winning song from…", options: ["Pocahontas", "Mulan", "Tarzan", "Hercules"], correct: 0, fact: "It swept the 1996 Academy Award and Golden Globe for Best Original Song." },
  { cat: "songs", q: "'When You Wish Upon a Star' — the studio's anthem — comes from…", options: ["Pinocchio", "Dumbo", "Fantasia", "Cinderella"], correct: 0, fact: "It won the 1940 Oscar and now opens nearly every Disney film." },
  { cat: "songs", q: "'I'll Make a Man Out of You' is the training montage anthem from…", options: ["Mulan", "Hercules", "Tarzan", "Aladdin"], correct: 0, fact: "Donny Osmond provides Shang's singing voice." },
  { cat: "songs", q: "Phil Collins wrote the songs for which Disney animated film?", options: ["Tarzan", "Hercules", "Mulan", "Pocahontas"], correct: 0, fact: "'You'll Be in My Heart' won him an Academy Award in 2000." },
  { cat: "songs", q: "'Remember Me' is the heart-tugging song of which Pixar film?", options: ["Coco", "Up", "Soul", "Brave"], correct: 0, fact: "It won the 2018 Oscar for Best Original Song." },
  { cat: "songs", q: "'Almost There' is the jazzy 'I want' song from…", options: ["The Princess and the Frog", "Tangled", "Moana", "Coco"], correct: 0, fact: "Its Art Deco animation style pays tribute to 1920s illustrator Aaron Douglas." },
  { cat: "songs", q: "'Friend Like Me' is belted out by which character?", options: ["The Genie", "Aladdin", "Jafar", "The Sultan"], correct: 0, fact: "Robin Williams recorded so many takes that animators built the visuals to match him." },
  { cat: "songs", q: "'Part of Your World' is sung by which longing heroine?", options: ["Ariel", "Belle", "Jasmine", "Moana"], correct: 0, fact: "Executives nearly cut it for 'boring' kids in test screenings — thank goodness they didn't." },

  // ============================ VOICE ACTORS ============================
  { cat: "voices", q: "Who voiced the Genie in the 1992 animated 'Aladdin'?", options: ["Robin Williams", "Eddie Murphy", "Jim Carrey", "Steve Martin"], correct: 0, fact: "He improvised so much the film was disqualified from a Best Screenplay nod." },
  { cat: "voices", q: "Who voiced Woody in the 'Toy Story' films?", options: ["Tim Allen", "Tom Hanks", "Billy Crystal", "John Ratzenberger"], correct: 1, fact: "Tom Hanks' brother Jim voices Woody in the theme parks and video games." },
  { cat: "voices", q: "Who voiced Buzz Lightyear in the 'Toy Story' films?", options: ["Tim Allen", "Tom Hanks", "Tim Curry", "Tom Hardy"], correct: 0, fact: "Allen improvised Buzz's clueless confidence from day one." },
  { cat: "voices", q: "Who voiced Elsa in 'Frozen'?", options: ["Kristen Bell", "Idina Menzel", "Auli'i Cravalho", "Mandy Moore"], correct: 1, fact: "Idina Menzel first won a Tony originating Elphaba in Broadway's 'Wicked.'" },
  { cat: "voices", q: "Who voiced Anna in 'Frozen'?", options: ["Kristen Bell", "Idina Menzel", "Mandy Moore", "Zendaya"], correct: 0, fact: "Bell recorded some early takes while pregnant, which shaped Anna's breathless energy." },
  { cat: "voices", q: "Who provides the voice of Moana?", options: ["Auli'i Cravalho", "Zendaya", "Idina Menzel", "Kristen Bell"], correct: 0, fact: "Auli'i was 14 and had submitted her audition tape almost as an afterthought." },
  { cat: "voices", q: "Who voices the demigod Maui in 'Moana'?", options: ["Dwayne Johnson", "Jason Momoa", "John Cena", "Kevin Hart"], correct: 0, fact: "'You're Welcome' was The Rock's first-ever movie musical number." },
  { cat: "voices", q: "Who voiced Mike Wazowski in 'Monsters, Inc.'?", options: ["Billy Crystal", "John Goodman", "Steve Buscemi", "Ben Stiller"], correct: 0, fact: "Crystal later said turning down Buzz Lightyear was his biggest career regret — until Mike." },
  { cat: "voices", q: "Who voiced the big blue Sulley in 'Monsters, Inc.'?", options: ["John Goodman", "Billy Crystal", "John Ratzenberger", "Tom Hanks"], correct: 0, fact: "Sulley has over two million individually animated hairs." },
  { cat: "voices", q: "Who voiced Dory in 'Finding Nemo'?", options: ["Ellen DeGeneres", "Whoopi Goldberg", "Oprah Winfrey", "Rosie O'Donnell"], correct: 0, fact: "Director Andrew Stanton wrote the part specifically for Ellen after watching her show." },
  { cat: "voices", q: "Who voiced the big blue Genie in the 2019 LIVE-ACTION 'Aladdin'?", options: ["Will Smith", "Kevin Hart", "Chris Rock", "Jamie Foxx"], correct: 0, fact: "Smith gave 'Friend Like Me' a hip-hop makeover for the remake." },
  { cat: "voices", q: "Who voiced the villainous Hades in 'Hercules'?", options: ["James Woods", "Jeremy Irons", "Tim Curry", "Danny DeVito"], correct: 0, fact: "Woods loved the fast-talking role so much he's reprised it for decades of spin-offs." },
  { cat: "voices", q: "Who voiced Scar in the 1994 'The Lion King'?", options: ["Jeremy Irons", "James Earl Jones", "Nathan Lane", "Tony Goldwyn"], correct: 0, fact: "Irons reportedly strained his voice belting 'Be Prepared,' so another singer finished it." },
  { cat: "voices", q: "Who provided the unmistakable voice of Mufasa in 1994?", options: ["James Earl Jones", "Jeremy Irons", "Morgan Freeman", "Nathan Lane"], correct: 0, fact: "Jones returned to voice Mufasa again in the 2019 photorealistic remake." },
  { cat: "voices", q: "Who voiced the icy superhero Frozone in 'The Incredibles'?", options: ["Samuel L. Jackson", "Idris Elba", "Denzel Washington", "Will Smith"], correct: 0, fact: "'Where is my SUPER SUIT?!' — one of the most quoted lines in Pixar history." },

  // ============================ FUN FACTS & TRIVIA ============================
  { cat: "funfacts", q: "What year did Disneyland open in Anaheim, California?", options: ["1949", "1955", "1961", "1971"], correct: 1, fact: "Opening day, July 17, 1955, was such a mess that staff dubbed it 'Black Sunday.'" },
  { cat: "funfacts", q: "What year did Walt Disney World open in Florida?", options: ["1955", "1965", "1971", "1982"], correct: 2, fact: "Walt died in 1966 and never saw the Florida park he'd dreamed up open in 1971." },
  { cat: "funfacts", q: "What was Mickey Mouse very nearly named instead?", options: ["Mortimer Mouse", "Marvin Mouse", "Milton Mouse", "Morris Mouse"], correct: 0, fact: "Walt's wife Lillian talked him out of 'Mortimer' — it sounded too pompous." },
  { cat: "funfacts", q: "Mickey Mouse's loyal pet dog is named…", options: ["Goofy", "Pluto", "Max", "Dinah"], correct: 1, fact: "Pluto and Goofy are both dogs — but only Goofy gets to talk and wear pants." },
  { cat: "funfacts", q: "Which 1928 short marked Mickey Mouse's debut with synchronized sound?", options: ["Steamboat Willie", "Plane Crazy", "The Band Concert", "Fantasia"], correct: 0, fact: "Its opening clip now plays before every modern Walt Disney Animation film." },
  { cat: "funfacts", q: "Disneyland's Sleeping Beauty Castle was inspired by a real castle in which country?", options: ["Germany", "France", "England", "Spain"], correct: 0, fact: "It echoes Neuschwanstein Castle in Bavaria." },
  { cat: "funfacts", q: "Which was the FIRST animated film ever nominated for the Best Picture Oscar?", options: ["Beauty and the Beast", "The Lion King", "Snow White", "Aladdin"], correct: 0, fact: "'Beauty and the Beast' earned the historic nod at the 1992 Academy Awards." },
  { cat: "funfacts", q: "'Frozen' is loosely based on which fairy tale?", options: ["The Snow Queen", "Cinderella", "Rapunzel", "The Little Match Girl"], correct: 0, fact: "Hans Christian Andersen's 'The Snow Queen' stumped Disney for nearly 70 years." },
  { cat: "funfacts", q: "'The Lion King' is loosely inspired by which Shakespeare play?", options: ["Hamlet", "Macbeth", "Romeo and Juliet", "King Lear"], correct: 0, fact: "A murdered king, a guilty uncle, a haunted heir — it's 'Hamlet' with fur." },
  { cat: "funfacts", q: "In '101 Dalmatians,' how many puppies are in Pongo and Perdita's original litter?", options: ["15", "21", "84", "101"], correct: 0, fact: "The 15 grow to 99 when they rescue the rest from Cruella." },
  { cat: "funfacts", q: "Which recurring vehicle is a famous Pixar Easter egg in nearly every film?", options: ["The Pizza Planet truck", "Lightning McQueen", "WALL-E's cooler", "The Millennium Falcon"], correct: 0, fact: "The battered yellow truck sneaks into almost every Pixar movie — spot it if you can." },
  { cat: "funfacts", q: "The Pixar Easter egg 'A113' is a reference to…", options: ["A classroom at CalArts", "Walt's office number", "A ride at Disneyland", "Walt's birthday"], correct: 0, fact: "It's the animation classroom where many Pixar founders studied." },
  { cat: "funfacts", q: "In which country is 'Mulan' set?", options: ["China", "Japan", "Korea", "Vietnam"], correct: 0, fact: "It's based on the ancient Chinese legend of Hua Mulan." },
  { cat: "funfacts", q: "In which country is 'Brave' set?", options: ["Scotland", "Ireland", "Wales", "England"], correct: 0, fact: "Merida's fiery red curls took Pixar years of new software to animate." },
  { cat: "funfacts", q: "What is the name of Pinocchio's pet goldfish?", options: ["Cleo", "Figaro", "Jiminy", "Blue"], correct: 0, fact: "Figaro the kitten and Cleo the goldfish share Geppetto's cozy workshop." },
];

module.exports = QUESTIONS;
module.exports.CATEGORIES = CATEGORIES;
